import React from 'react';
import {
  AbsoluteFill,
  useCurrentFrame,
  useVideoConfig,
  interpolate,
  spring,
  Sequence,
  Audio,
  staticFile,
} from 'remotion';

// Import the words (generated by make_narration.py)
import defibWords from './defib_words.json';

export const FPS = 30;
export const DURATION_IN_FRAMES = 1220;

const C = {
  bgDeep: '#0b0e14',
  bgPanel: '#12161f',
  gold: '#FFD23F',
  keyElectric: '#3FE0FF',
  heartRed: '#FF4D5E',
  chaosMagenta: '#E84CC4',
  flatlineCyan: '#7FF0D8',
  pulseGreen: '#4DF08A',
  gridGrey: '#1c2330',
  white: '#FFFFFF',
};

const clamp = { extrapolateLeft: 'clamp', extrapolateRight: 'clamp' } as const;

// Scene boundaries derived from narration
const S = {
  scene1: 0,
  scene2: 203,
  scene3: 254,
  scene4: 561,
  scene5: 932,
  scene6: 1132,
};

function SceneWrap({ children }: { children: React.ReactNode }) {
  const f = useCurrentFrame();
  const fadeIn = interpolate(f, [0, 8], [0, 1], clamp);
  const sc = interpolate(f, [0, 8], [1.06, 1.0], clamp);
  return (
    <div
      style={{
        position: 'absolute',
        inset: 0,
        opacity: fadeIn,
        transform: `scale(${sc})`,
        transformOrigin: 'center',
      }}
    >
      {children}
    </div>
  );
}

const Bg = () => (
  <AbsoluteFill style={{ backgroundColor: C.bgDeep }}>
    {/* ECG Grid Backdrop */}
    <svg width="1080" height="1920" style={{ position: 'absolute', inset: 0, opacity: 0.15 }}>
      <defs>
        <pattern id="grid" width="40" height="40" patternUnits="userSpaceOnUse">
          <path d="M 40 0 L 0 0 0 40" fill="none" stroke={C.gridGrey} strokeWidth="2" />
        </pattern>
        <pattern id="bigGrid" width="200" height="200" patternUnits="userSpaceOnUse">
          <rect width="200" height="200" fill="url(#grid)" />
          <path d="M 200 0 L 0 0 0 200" fill="none" stroke={C.gridGrey} strokeWidth="4" />
        </pattern>
      </defs>
      <rect width="1080" height="1920" fill="url(#bigGrid)" />
    </svg>
  </AbsoluteFill>
);

// ─── SVG VECTOR COMPONENTS ───────────────────────────────────────────────────

function HeartSilhouette({ scale = 1, cx = 540, cy = 960, stroke = 'none', fill = C.heartRed, strokeWidth = 8, opacity = 1 }) {
  return (
    <g transform={`translate(${cx}, ${cy}) scale(${scale}) translate(-540, -960)`} opacity={opacity}>
      <path
        d="M 540,1150 C 540,1150 320,950 320,750 C 320,620 420,520 540,650 C 660,520 760,620 760,750 C 760,950 540,1150 540,1150 Z"
        fill={fill}
        stroke={stroke}
        strokeWidth={strokeWidth}
        strokeLinejoin="round"
      />
    </g>
  );
}

function DefibPaddle({ cx = 540, cy = 960, scale = 1, angle = 0, opacity = 1, chargeFlash = 0 }) {
  return (
    <g transform={`translate(${cx}, ${cy}) rotate(${angle}) scale(${scale})`} opacity={opacity}>
      <rect x={-80} y={-30} width={160} height={60} rx={30} fill="#444" />
      <rect x={-100} y={-10} width={200} height={20} rx={10} fill="#222" />
      <path d="M -100,0 Q 0,40 100,0" fill="none" stroke={C.keyElectric} strokeWidth={8} opacity={0.8 + 0.2 * chargeFlash} />
    </g>
  );
}

function ECGLine({ cx = 540, cy = 960, mode = 'flatline', progress = 1 }) {
  let path = '';
  if (mode === 'flatline') {
    path = `M 140,${cy} L 940,${cy}`;
  } else if (mode === 'frantic') {
    path = `M 140,${cy} L 240,${cy - 80} L 300,${cy + 120} L 380,${cy - 50} L 460,${cy + 90} L 550,${cy - 110} L 630,${cy + 80} L 720,${cy - 60} L 800,${cy + 130} L 880,${cy - 40} L 940,${cy}`;
  } else if (mode === 'clean') {
    path = `M 140,${cy} L 440,${cy} L 480,${cy - 30} L 500,${cy} L 520,${cy + 20} L 540,${cy - 120} L 560,${cy + 40} L 580,${cy} L 620,${cy - 40} L 660,${cy} L 940,${cy}`;
  }

  return (
    <path
      d={path}
      fill="none"
      stroke={mode === 'clean' ? C.pulseGreen : mode === 'frantic' ? C.chaosMagenta : C.flatlineCyan}
      strokeWidth={6}
      strokeLinejoin="round"
      strokeDasharray="1000"
      strokeDashoffset={1000 * (1 - progress)}
      opacity={0.8}
    />
  );
}

// ─── SCENE 1: HOOK ────────────────────────────────────────────────────────────
function SceneHook() {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();

  // Heart stroke draws in (0-10), fills red spring pop (10+)
  const heartStroke = interpolate(frame, [0, 10], [0, 1], clamp);
  const heartScale = spring({ frame: frame - 10, fps, config: { damping: 12, mass: 0.5, stiffness: 180 } });

  // Paddles slide in (15-30)
  const padTopY = interpolate(frame, [15, 30], [200, 500], clamp);
  const padBotY = interpolate(frame, [15, 30], [1720, 1200], clamp);

  // CLEAR badge slams in (25+)
  const badgeScale = spring({ frame: frame - 25, fps, config: { damping: 12, mass: 0.5, stiffness: 200 } });
  
  // RESTARTS IT? tags drops (33+)
  const tagScale = spring({ frame: frame - 33, fps, config: { damping: 14, mass: 0.5, stiffness: 180 } });

  // Flatline pulse crawls (40-100)
  const ecgProgress = interpolate(frame, [40, 100], [0, 1], clamp);
  const chargeFlash = Math.sin(frame * 0.5);

  return (
    <AbsoluteFill>
      <Bg />
      <SceneWrap>
        <svg viewBox="0 0 1080 1920" width={1080} height={1920} style={{ position: 'absolute', inset: 0 }}>
          
          {/* Heart */}
          {frame < 10 && (
            <HeartSilhouette 
              scale={0.5 + 0.5 * heartStroke} 
              fill="none" 
              stroke={C.heartRed} 
              strokeWidth={12} 
              opacity={heartStroke} 
            />
          )}
          {frame >= 10 && (
            <HeartSilhouette scale={0.5 + 0.5 * heartScale} opacity={0.6} /> // Dim and motionless
          )}

          {/* Paddles */}
          <DefibPaddle cx={540} cy={padTopY} chargeFlash={chargeFlash} />
          <DefibPaddle cx={540} cy={padBotY} angle={180} chargeFlash={chargeFlash} />

          {/* Badges */}
          {badgeScale > 0.01 && (
            <g transform={`translate(820, 200) scale(${badgeScale})`}>
              <rect x={-150} y={-40} width={300} height={80} rx={40} fill={C.gold} />
              <text x={0} y={15} textAnchor="middle" fill={C.bgDeep} fontSize={45} fontWeight={900} fontFamily="Poppins, Arial Black">CLEAR</text>
            </g>
          )}
          {tagScale > 0.01 && (
            <g transform={`translate(820, 300) scale(${tagScale})`}>
              <rect x={-120} y={-25} width={240} height={50} rx={10} fill={C.bgPanel} stroke={C.gold} strokeWidth={2} />
              <text x={0} y={8} textAnchor="middle" fill={C.gold} fontSize={25} fontWeight={900} fontFamily="Poppins, Arial Black">RESTARTS IT?</text>
            </g>
          )}

          {/* ECG Flatline */}
          <ECGLine cy={1500} mode="flatline" progress={ecgProgress} />

        </svg>
      </SceneWrap>
    </AbsoluteFill>
  );
}

// ─── SCENE 2: OPPOSITE ─────────────────────────────────────────────────────────
function SceneOpposite() {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();

  // Words slam in staggered
  const stagger = 2;
  const word = "OPPOSITE";
  const scales = word.split('').map((_, i) => 
    spring({ frame: frame - (i * stagger), fps, config: { damping: 12, mass: 0.5, stiffness: 180 } })
  );

  // Arrow draws on then flips
  const arrowDraw = interpolate(frame, [15, 30], [0, 1], clamp);
  const arrowFlip = spring({ frame: frame - 35, fps, config: { damping: 14, mass: 0.6, stiffness: 160 } });
  
  // Heart shrinks to corner
  const heartScale = spring({ frame, fps, config: { damping: 15, mass: 0.5, stiffness: 150 } });

  return (
    <AbsoluteFill style={{ backgroundColor: C.bgDeep }}>
      <svg viewBox="0 0 1080 1920" width={1080} height={1920} style={{ position: 'absolute', inset: 0 }}>
        
        {/* Tiny heart in corner */}
        <g transform={`translate(100, 100) scale(${interpolate(heartScale, [0, 1], [1, 0.2])}) translate(-540, -960)`}>
          <HeartSilhouette opacity={0.3} />
        </g>

        {/* Big Word */}
        <g transform="translate(540, 960)">
          {/* Flash pulse */}
          <circle cx={0} cy={0} r={300} fill={C.gold} opacity={Math.max(0, 0.2 - frame * 0.01)} />
          
          <text textAnchor="middle" fontSize={120} fontWeight={900} fontFamily="Poppins, Arial Black" letterSpacing={10}>
            {word.split('').map((char, i) => (
              <tspan key={i} fill={C.gold} dy={0} style={{ display: 'inline-block', transform: `scale(${scales[i]})` }}>
                {char}
              </tspan>
            ))}
          </text>
        </g>

        {/* Looping Arrow */}
        <g transform={`translate(540, 960) rotate(${arrowFlip * 180})`}>
          <path 
            d="M -300,-150 C -400,-300 400,-300 300,-150" 
            fill="none" 
            stroke={C.white} 
            strokeWidth={15} 
            strokeDasharray="1000" 
            strokeDashoffset={1000 * (1 - arrowDraw)}
          />
          <path d="M -320,-170 L -280,-130 L -330,-110 Z" fill={C.white} opacity={arrowDraw > 0.9 ? 1 : 0} />
          <path d="M 320,-170 L 280,-130 L 330,-110 Z" fill={C.white} opacity={arrowDraw > 0.9 ? 1 : 0} />
        </g>

      </svg>
    </AbsoluteFill>
  );
}

// Helper to generate a heart lattice (approximate bounds)
const CELL_SIZE = 40;
const cells: {x: number, y: number, r: number}[] = [];
for (let y = 600; y <= 1100; y += 45) {
  for (let x = 350; x <= 730; x += 45) {
    // Simple bounding check for heart shape roughly
    const dx = x - 540;
    const dy = y - 750;
    const dist = Math.sqrt(dx*dx + dy*dy);
    // Rough heart check
    if (dist < 220 || (y > 750 && dx*dx + (y - 850)*(y - 850)*0.5 < 40000)) {
      if (Math.random() > 0.2) {
        cells.push({ x, y, r: Math.random() }); // r is a random seed per cell
      }
    }
  }
}

// ─── SCENE 3: CHAOS ────────────────────────────────────────────────────────────
function SceneChaos() {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();

  // Cells pop in (0-20)
  const cellScale = spring({ frame, fps, config: { damping: 15, mass: 0.5, stiffness: 180 } });

  // Frantic ECG draws (15-60)
  const ecgProgress = interpolate(frame, [15, 60], [0, 1], clamp);

  // NO BLOOD FLOW badge
  const pillScale = spring({ frame: frame - 30, fps, config: { damping: 12, mass: 0.5, stiffness: 200 } });

  return (
    <AbsoluteFill>
      <Bg />
      <SceneWrap>
        <svg viewBox="0 0 1080 1920" width={1080} height={1920} style={{ position: 'absolute', inset: 0 }}>
          
          {/* Cell Lattice (Quivering) */}
          {cells.map((c, i) => {
            // Flicker logic: random phase based on seed
            const flicker = Math.sin(frame * 0.5 + c.r * 10);
            const color = flicker > 0 ? C.heartRed : C.chaosMagenta;
            const pop = spring({ frame: frame - c.r * 15, fps, config: { damping: 10, mass: 0.4, stiffness: 200 } });
            
            // Jitter position
            const jx = Math.sin(frame * 1.3 + c.r * 5) * 3;
            const jy = Math.cos(frame * 1.1 + c.r * 7) * 3;

            return (
              <rect 
                key={i} 
                x={c.x - CELL_SIZE/2 + jx} 
                y={c.y - CELL_SIZE/2 + jy} 
                width={CELL_SIZE} 
                height={CELL_SIZE} 
                rx={10} 
                fill={color} 
                transform={`scale(${pop})`}
                transform-origin={`${c.x}px ${c.y}px`}
              />
            );
          })}

          {/* Random Sparks */}
          {frame % 4 === 0 && (
            <path 
              d={`M ${540 + Math.random()*200 - 100},${800 + Math.random()*200} L ${540 + Math.random()*200 - 100},${800 + Math.random()*200}`} 
              stroke={C.keyElectric} 
              strokeWidth={3} 
            />
          )}

          {/* Blood Vessels (stalled) */}
          <g opacity={cellScale}>
            <path d="M 450,550 L 450,400" stroke={C.heartRed} strokeWidth={20} strokeLinecap="round" />
            <path d="M 630,550 L 630,400" stroke={C.chaosMagenta} strokeWidth={20} strokeLinecap="round" />
            {/* Stalled blood dots */}
            <circle cx={450} cy={480 + Math.sin(frame*0.2)*10} r={15} fill={C.white} opacity={0.8} />
            <circle cx={630} cy={460 + Math.cos(frame*0.2)*10} r={15} fill={C.white} opacity={0.8} />
          </g>

          {/* Frantic ECG */}
          <ECGLine cy={1500} mode="frantic" progress={ecgProgress} />

          {/* Badge */}
          {pillScale > 0.01 && (
            <g transform={`translate(540, 1300) scale(${pillScale})`}>
              <rect x={-140} y={-30} width={280} height={60} rx={15} fill={C.bgPanel} stroke={C.heartRed} strokeWidth={2} />
              <text x={0} y={10} textAnchor="middle" fill={C.chaosMagenta} fontSize={28} fontWeight={900} fontFamily="Poppins, Arial Black">NO BLOOD FLOW</text>
            </g>
          )}

        </svg>
      </SceneWrap>
    </AbsoluteFill>
  );
}

// ─── SCENE 4: SHOCK ────────────────────────────────────────────────────────────
function SceneShock() {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();

  // Lightning bolt strikes (0-6 frames)
  const strike = interpolate(frame, [0, 6], [0, 1], clamp);
  
  // Wavefront sweeps top to bottom (10-40 frames)
  const wavefrontY = interpolate(frame, [10, 40], [500, 1200], clamp);

  // Shock ring expands (10-22)
  const ringScale = interpolate(frame, [10, 22], [0, 2.5], clamp);
  const ringOpacity = interpolate(frame, [10, 22], [1, 0], clamp);

  // Unison pop after sweep (45+)
  const lockPop = spring({ frame: frame - 45, fps, config: { damping: 13, mass: 0.5, stiffness: 180 } });

  // RESET badge (50+)
  const resetScale = spring({ frame: frame - 50, fps, config: { damping: 10, mass: 0.6, stiffness: 200 } });

  return (
    <AbsoluteFill>
      <Bg />
      <SceneWrap>
        <svg viewBox="0 0 1080 1920" width={1080} height={1920} style={{ position: 'absolute', inset: 0 }}>
          
          {/* Paddles back in frame */}
          <DefibPaddle cx={540} cy={200} />
          <DefibPaddle cx={540} cy={1720} angle={180} />

          {/* Cell Lattice (WAVEFRONT SYNC) */}
          {cells.map((c, i) => {
            const isSynced = c.y < wavefrontY;
            
            // Before sync, flicker. After sync, lock to uniform cyan, then pop.
            const flicker = Math.sin(frame * 0.5 + c.r * 10);
            const color = isSynced ? C.flatlineCyan : (flicker > 0 ? C.heartRed : C.chaosMagenta);
            
            // Scale logic
            let s = 1;
            if (!isSynced) {
              s = 1 + Math.sin(frame * 1.3 + c.r * 5) * 0.05; // Jitter
            } else if (frame > 45) {
              // The lock pop
              s = interpolate(lockPop, [0, 1], [1, 0.9]); // Compress slightly
            }

            return (
              <rect 
                key={i} 
                x={c.x - CELL_SIZE/2} 
                y={c.y - CELL_SIZE/2} 
                width={CELL_SIZE} 
                height={CELL_SIZE} 
                rx={10} 
                fill={color} 
                transform={`scale(${s})`}
                transform-origin={`${c.x}px ${c.y}px`}
                opacity={isSynced ? 0.5 : 1} // Dim when locked
              />
            );
          })}

          {/* Lightning Bolt */}
          {strike > 0 && strike < 1 && (
            <path 
              d="M 540,200 L 510,400 L 570,600 L 520,800 L 560,1000 L 540,1200" 
              fill="none" 
              stroke={C.white} 
              strokeWidth={30} 
              strokeDasharray="2000"
              strokeDashoffset={2000 * (1 - strike)}
              opacity={0.9}
            />
          )}

          {/* Shock Ring */}
          {frame >= 10 && frame < 22 && (
            <circle 
              cx={540} cy={850} 
              r={150 * ringScale} 
              fill="none" 
              stroke={C.keyElectric} 
              strokeWidth={15} 
              opacity={ringOpacity} 
            />
          )}

          {/* Full frame white flash on impact */}
          {frame === 6 && <rect width="1080" height="1920" fill={C.white} opacity={0.5} />}

          {/* ECG Overwrite (Frantic -> Flatline) */}
          <g opacity={frame < 45 ? 1 : 0}>
            <ECGLine cy={1500} mode="frantic" progress={1} />
          </g>
          {frame >= 45 && (
            <ECGLine cy={1500} mode="flatline" progress={1} />
          )}

          {/* RESET Badge */}
          {resetScale > 0.01 && (
            <g transform={`translate(540, 850) scale(${resetScale})`}>
              {/* Flash behind */}
              <circle cx={0} cy={0} r={120} fill={C.gold} opacity={0.2} />
              <rect x={-120} y={-40} width={240} height={80} rx={20} fill={C.gold} />
              <text x={0} y={15} textAnchor="middle" fill={C.bgDeep} fontSize={40} fontWeight={900} fontFamily="Poppins, Arial Black">RESET</text>
            </g>
          )}

        </svg>
      </SceneWrap>
    </AbsoluteFill>
  );
}

// ─── SCENE 5: PACEMAKER ────────────────────────────────────────────────────────
function ScenePacemaker() {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();

  // SA Node lights up (10+)
  const saScale = spring({ frame: frame - 10, fps, config: { damping: 14, mass: 0.5, stiffness: 200 } });
  
  // Radial green wave (30-90)
  const waveRadius = interpolate(frame, [30, 90], [0, 800], clamp);

  // Heart beat pump (80+)
  const pump = spring({ frame: frame - 80, fps, config: { damping: 10, mass: 0.7, stiffness: 150 } }); // Overshoot then settle
  const beatScale = interpolate(pump, [0, 1], [1, 1.05]);

  // Clean ECG draws (70-130)
  const ecgProgress = interpolate(frame, [70, 130], [0, 1], clamp);

  return (
    <AbsoluteFill>
      <Bg />
      <SceneWrap>
        <svg viewBox="0 0 1080 1920" width={1080} height={1920} style={{ position: 'absolute', inset: 0 }}>
          
          <g transform={`scale(${beatScale})`} transform-origin="540px 850px">
            {/* Cell Lattice (RADIAL GREEN) */}
            {cells.map((c, i) => {
              // SA node position approx (420, 650)
              const dist = Math.sqrt((c.x - 420)**2 + (c.y - 650)**2);
              const isHealthy = dist < waveRadius;
              
              const color = isHealthy ? C.pulseGreen : C.flatlineCyan;
              const opacity = isHealthy ? 0.9 : 0.5;

              return (
                <rect 
                  key={i} 
                  x={c.x - CELL_SIZE/2} 
                  y={c.y - CELL_SIZE/2} 
                  width={CELL_SIZE} 
                  height={CELL_SIZE} 
                  rx={10} 
                  fill={color} 
                  opacity={opacity}
                />
              );
            })}

            {/* SA Node */}
            {saScale > 0.01 && (
              <g transform={`translate(420, 650) scale(${saScale})`}>
                <circle cx={0} cy={0} r={40} fill={C.gold} />
                <circle cx={0} cy={0} r={60} fill={C.gold} opacity={0.3} />
                {/* PACEMAKER label */}
                <rect x={-80} y={-70} width={160} height={40} rx={10} fill={C.bgPanel} stroke={C.gold} strokeWidth={2} />
                <text x={0} y={-42} textAnchor="middle" fill={C.gold} fontSize={20} fontWeight={900} fontFamily="Poppins, Arial Black">PACEMAKER</text>
              </g>
            )}

            {/* Blood flowing out on beat */}
            <g opacity={pump}>
              <path d="M 450,550 L 450,300" stroke={C.pulseGreen} strokeWidth={20} strokeLinecap="round" opacity={0.2} />
              <path d="M 630,550 L 630,300" stroke={C.pulseGreen} strokeWidth={20} strokeLinecap="round" opacity={0.2} />
              {/* Flowing blood dots */}
              <circle cx={450} cy={500 - (frame - 80)*8} r={15} fill={C.pulseGreen} />
              <circle cx={630} cy={520 - (frame - 80)*8} r={15} fill={C.pulseGreen} />
            </g>
          </g>

          {/* Clean ECG */}
          <ECGLine cy={1500} mode="clean" progress={ecgProgress} />

        </svg>
      </SceneWrap>
    </AbsoluteFill>
  );
}

// ─── SCENE 6: PAYOFF ───────────────────────────────────────────────────────────
function ScenePayoff() {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();

  // Words slam in (3 beats)
  const w1 = spring({ frame: frame - 10, fps, config: { damping: 12, mass: 0.5, stiffness: 200 } });
  const w2 = spring({ frame: frame - 35, fps, config: { damping: 12, mass: 0.5, stiffness: 200 } });
  const w3 = spring({ frame: frame - 60, fps, config: { damping: 12, mass: 0.5, stiffness: 200 } });

  // Heart continuous steady beat (every ~30 frames)
  const beat = (Math.sin(frame * 0.2) + 1) * 0.5; // 0 to 1
  const hScale = 0.5 + beat * 0.05;

  // Gold underline sweeps (70-90)
  const lineDraw = interpolate(frame, [70, 90], [0, 1], clamp);

  return (
    <AbsoluteFill>
      <Bg />
      <SceneWrap>
        <svg viewBox="0 0 1080 1920" width={1080} height={1920} style={{ position: 'absolute', inset: 0 }}>
          
          {/* Small beating heart at top */}
          <HeartSilhouette scale={hScale} cx={540} cy={400} fill={C.pulseGreen} />
          {/* Pulse glyph blinks */}
          <circle cx={680} cy={350} r={15 * (frame % 20 < 10 ? 1 : 0)} fill={C.gold} />

          {/* Punchline text */}
          <g transform="translate(540, 1100)">
            {w1 > 0.01 && (
              <text x={0} y={-180} textAnchor="middle" fill={C.white} fontSize={70} fontWeight={900} fontFamily="Poppins, Arial Black" transform={`scale(${w1})`}>
                SHOCK IT
              </text>
            )}
            
            {w2 > 0.01 && (
              <g transform={`scale(${w2})`}>
                {/* Red flash resolving to gold */}
                <text x={0} y={-40} textAnchor="middle" fill={frame < 45 ? C.heartRed : C.gold} fontSize={90} fontWeight={900} fontFamily="Poppins, Arial Black">
                  TO DEATH
                </text>
              </g>
            )}
            
            {w3 > 0.01 && (
              <g transform={`scale(${w3})`}>
                {/* Flash fill */}
                <circle cx={0} cy={80} r={300 * Math.max(0, 1 - (frame-60)*0.1)} fill={C.gold} opacity={0.3} />
                <text x={0} y={100} textAnchor="middle" fill={C.gold} fontSize={110} fontWeight={900} fontFamily="Poppins, Arial Black">
                  TO LIVE
                </text>
              </g>
            )}

            {/* Gold Underline */}
            {frame > 70 && (
              <path 
                d="M -300,150 L 300,150" 
                fill="none" 
                stroke={C.gold} 
                strokeWidth={15} 
                strokeLinecap="round"
                strokeDasharray="600"
                strokeDashoffset={600 * (1 - lineDraw)}
              />
            )}
          </g>

        </svg>
      </SceneWrap>
    </AbsoluteFill>
  );
}

// ─── MASTER COMPOSITION ───────────────────────────────────────────────────────
export const Defib: React.FC = () => {
  return (
    <AbsoluteFill style={{ backgroundColor: C.bgDeep }}>
      {/* Audio Layer */}
      <Audio src={staticFile('defib_narration.mp3')} />
      <Audio src={staticFile('music.mp3')} volume={0.12} />

      {/* Baked Scene SFX triggers (from defib.json plan) */}
      <Sequence from={0} durationInFrames={200}>
        <Audio src={staticFile('sfx_chime.wav')} volume={0.4} />
      </Sequence>
      <Sequence from={S.scene2 + 15} durationInFrames={100}>
        <Audio src={staticFile('sfx_smack.wav')} volume={0.5} />
      </Sequence>
      <Sequence from={S.scene3} durationInFrames={300}>
        <Audio src={staticFile('sfx_digital.wav')} volume={0.3} />
      </Sequence>
      <Sequence from={S.scene4} durationInFrames={150}>
        <Audio src={staticFile('sfx_fever_boom.wav')} volume={0.6} />
      </Sequence>
      <Sequence from={S.scene5 + 70} durationInFrames={100}>
        <Audio src={staticFile('sfx_boing.wav')} volume={0.6} />
      </Sequence>
      <Sequence from={S.scene6 + 60} durationInFrames={100}>
        <Audio src={staticFile('sfx_success.wav')} volume={0.5} />
      </Sequence>

      {/* Visual Scenes */}
      <Sequence from={S.scene1} durationInFrames={S.scene2 - S.scene1}>
        <SceneHook />
      </Sequence>
      <Sequence from={S.scene2} durationInFrames={S.scene3 - S.scene2}>
        <SceneOpposite />
      </Sequence>
      <Sequence from={S.scene3} durationInFrames={S.scene4 - S.scene3}>
        <SceneChaos />
      </Sequence>
      <Sequence from={S.scene4} durationInFrames={S.scene5 - S.scene4}>
        <SceneShock />
      </Sequence>
      <Sequence from={S.scene5} durationInFrames={S.scene6 - S.scene5}>
        <ScenePacemaker />
      </Sequence>
      <Sequence from={S.scene6} durationInFrames={DURATION_IN_FRAMES - S.scene6}>
        <ScenePayoff />
      </Sequence>
    </AbsoluteFill>
  );
};
