python make_narration.py --txt "..\..\reimagined transcripts\076_speed-of-light-delay.txt" --slug t076
python make_narration.py --txt "..\..\reimagined transcripts\077_venus-crushing-pressure.txt" --slug t077
python make_narration.py --txt "..\..\reimagined transcripts\078_saturn-floats-on-water.txt" --slug t078
python make_narration.py --txt "..\..\reimagined transcripts\079_no-sound-in-space.txt" --slug t079
python make_narration.py --txt "..\..\reimagined transcripts\080_diamond-rain-planets.txt" --slug t080
python make_narration.py --txt "..\..\reimagined transcripts\081_lifetime-saliva-pools.txt" --slug t081
python make_narration.py --txt "..\..\reimagined transcripts\082_blood-vessels-circle-earth.txt" --slug t082
python make_narration.py --txt "..\..\reimagined transcripts\083_ants-outweigh-humans.txt" --slug t083
python make_narration.py --txt "..\..\reimagined transcripts\084_money-printed-daily.txt" --slug t084
python make_narration.py --txt "..\..\reimagined transcripts\085_lightning-strikes-per-second.txt" --slug t085
python make_narration.py --txt "..\..\reimagined transcripts\086_hair-growth-marathon.txt" --slug t086
python make_narration.py --txt "..\..\reimagined transcripts\087_ocean-salt-buries-continents.txt" --slug t087
python make_narration.py --txt "..\..\reimagined transcripts\088_bacteria-on-your-body.txt" --slug t088
python make_narration.py --txt "..\..\reimagined transcripts\089_earth-cosmic-dust-daily.txt" --slug t089
python make_narration.py --txt "..\..\reimagined transcripts\090_breaths-fill-balloons.txt" --slug t090
python make_narration.py --txt "..\..\reimagined transcripts\091_marshmallow-test-willpower.txt" --slug t091
python make_narration.py --txt "..\..\reimagined transcripts\092_bystander-effect-murder.txt" --slug t092
python make_narration.py --txt "..\..\reimagined transcripts\093_barrel-niagara-stunt.txt" --slug t093
python make_narration.py --txt "..\..\reimagined transcripts\094_milgram-shock-obedience.txt" --slug t094
python make_narration.py --txt "..\..\reimagined transcripts\095_dancing-plague-1518-2.txt" --slug t095
python make_narration.py --txt "..\..\reimagined transcripts\096_hot-dog-eating-record.txt" --slug t096
python make_narration.py --txt "..\..\reimagined transcripts\097_texting-driver-bridge.txt" --slug t097
python make_narration.py --txt "..\..\reimagined transcripts\098_placebo-fake-surgery.txt" --slug t098
python make_narration.py --txt "..\..\reimagined transcripts\099_diver-cave-wrong-turn.txt" --slug t099
python make_narration.py --txt "..\..\reimagined transcripts\100_stanford-prison-guards.txt" --slug t100
