call pipeline.bat Corpse corpse "R056 - Corpse Medicine in Europe"
call pipeline.bat Beerflood beerflood "R057 - The London Beer Flood"
call pipeline.bat Monks monks "R058 - Self Mummifying Monks"
call pipeline.bat Stink stink "R059 - The Great Stink"
call pipeline.bat Fugates fugates "R060 - Blue Fugates of Kentucky"
call pipeline.bat Blackhole blackhole "R061 - Fall into a Black Hole"
call pipeline.bat Elevator elevator "R062 - Ride Elevator to Space"
call pipeline.bat Mercury mercury "R063 - Swim in Pool of Mercury"
call pipeline.bat Trench trench "R064 - Survive Fall into Marianas Trench"
call pipeline.bat Jupiter jupiter "R065 - Stand on Jupiter Surface"
call pipeline.bat Fridge fridge "R066 - Hide in Fridge from Nuke"
